name: java-ci-workflows

on:
  pull_request:
    branches:
      - "develop"

jobs:
  check-application:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
          MYSQL_DATABASE: todolistdb

        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for MySQL to be ready
        run: |
          echo "Aguardando MySQL iniciar..."
          for i in {1..20}; do
          nc -z 127.0.0.1 3306 && echo "MySQL está pronto!" && break
          echo "Esperando MySQL... tentativa $i"
          sleep 3
          done

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: todolistdb
          DB_USERNAME: root
          DB_PASSWORD: ${{secrets.MYSQL_PASSWORD}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: user/app:latest